apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service-deployment
  namespace: ride-share-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      imagePullSecrets:
      - name: ghcr-login-secret
      containers:
      - name: matching-service
        image: ghcr.io/mouli018/matching-service:75419a2bde621837ba1194ecd5d823662bb9e356
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: ride-share-prod
spec:
  selector:
    app: matching-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
